import 'package:timezone/timezone.dart' as tz;

import '../../shared/utils/booking_time.dart';
import '../../shared/utils/working_hours.dart';

enum BookingRequestHoursFit {
  withinPublishedHours,
  outsidePublishedHours,
  noPublishedHours,
}

tz.Location bookingRequestLocation(String timezone) =>
    bookingTimeLocation(timezone);

enum BookingRequestTimeIssue { unspecified, invalid, repeatedHour }

/// Parsed customer preference, kept separate from any owner-selected replacement.
/// Text is accepted only in the unambiguous format generated by the public form.
class BookingRequestTimeResolution {
  final DateTime? date;
  final int? hour;
  final int? minute;
  final DateTime? instantUtc;
  final BookingRequestTimeIssue? issue;

  const BookingRequestTimeResolution({
    this.date,
    this.hour,
    this.minute,
    this.instantUtc,
    this.issue,
  });
}

BookingRequestTimeResolution resolveBookingRequestTime({
  required String timezone,
  DateTime? requestedFor,
  String? preferredTimeText,
}) {
  bookingRequestLocation(timezone);
  if (requestedFor != null) {
    final wall = bookingRequestWallClock(
      requestedForUtc: requestedFor,
      timezone: timezone,
    );
    return BookingRequestTimeResolution(
      date: DateTime.utc(wall.year, wall.month, wall.day),
      hour: wall.hour,
      minute: wall.minute,
      instantUtc: requestedFor.toUtc(),
    );
  }
  final match = RegExp(
    r'^(\d{4})-(\d{2})-(\d{2})(?:\s+at\s+(\d{2}):(\d{2}))?$',
  ).firstMatch(preferredTimeText?.trim() ?? '');
  if (match == null) {
    return const BookingRequestTimeResolution(
      issue: BookingRequestTimeIssue.unspecified,
    );
  }
  final year = int.parse(match[1]!);
  final month = int.parse(match[2]!);
  final day = int.parse(match[3]!);
  final date = DateTime.utc(year, month, day);
  if (year < 1 || date.year != year || date.month != month || date.day != day) {
    return const BookingRequestTimeResolution(
      issue: BookingRequestTimeIssue.invalid,
    );
  }
  if (match[4] == null) {
    return BookingRequestTimeResolution(
      date: date,
      issue: BookingRequestTimeIssue.unspecified,
    );
  }
  final hour = int.parse(match[4]!);
  final minute = int.parse(match[5]!);
  final instants = bookingRequestPossibleInstants(
    date: date,
    hour: hour,
    minute: minute,
    timezone: timezone,
  );
  if (instants.isEmpty) {
    return BookingRequestTimeResolution(
      date: date,
      issue: BookingRequestTimeIssue.invalid,
    );
  }
  return BookingRequestTimeResolution(
    date: date,
    hour: hour,
    minute: minute,
    instantUtc: instants.length == 1 ? instants.single : null,
    issue: instants.length > 1 ? BookingRequestTimeIssue.repeatedHour : null,
  );
}

/// All real instants for a civil minute. Empty means a clock-change gap;
/// two results mean a repeated hour which needs an explicit occurrence choice.
List<DateTime> bookingRequestPossibleInstants({
  required DateTime date,
  required int hour,
  required int minute,
  required String timezone,
}) {
  final location = bookingRequestLocation(timezone);
  if (hour < 0 || hour > 23 || minute < 0 || minute > 59) return const [];
  final wall = DateTime.utc(date.year, date.month, date.day, hour, minute);
  final candidates = <DateTime>{};
  for (final offset in location.zones.map((zone) => zone.offset).toSet()) {
    final candidate = wall.subtract(Duration(milliseconds: offset));
    final local = tz.TZDateTime.from(candidate, location);
    if (local.year == date.year &&
        local.month == date.month &&
        local.day == date.day &&
        local.hour == hour &&
        local.minute == minute) {
      candidates.add(candidate);
    }
  }
  return candidates.toList()..sort();
}

String bookingRequestOccurrenceLabel(DateTime instant, String timezone) {
  final local = tz.TZDateTime.from(instant, bookingRequestLocation(timezone));
  final offset = local.timeZoneOffset;
  final hours = offset.inMinutes.abs() ~/ 60;
  final minutes = offset.inMinutes.abs() % 60;
  final sign = offset.isNegative ? '−' : '+';
  return '${local.timeZoneName} (UTC$sign${hours.toString().padLeft(2, '0')}:${minutes.toString().padLeft(2, '0')})';
}

DateTime bookingRequestUtcFromWallClock({
  required DateTime date,
  required int hour,
  required int minute,
  required String timezone,
  DateTime? preferredInstantUtc,
}) {
  final location = bookingRequestLocation(timezone);
  // A repeated autumn clock time represents two instants. Keep the customer's
  // exact choice while the owner has left its displayed date/time unchanged.
  if (preferredInstantUtc != null) {
    final preferred = tz.TZDateTime.from(preferredInstantUtc.toUtc(), location);
    if (preferred.year == date.year &&
        preferred.month == date.month &&
        preferred.day == date.day &&
        preferred.hour == hour &&
        preferred.minute == minute) {
      return preferredInstantUtc.toUtc();
    }
  }
  final zoned = tz.TZDateTime(
    location,
    date.year,
    date.month,
    date.day,
    hour,
    minute,
  );
  if (zoned.year != date.year ||
      zoned.month != date.month ||
      zoned.day != date.day ||
      zoned.hour != hour ||
      zoned.minute != minute) {
    throw ArgumentError.value(
      '$date $hour:$minute',
      'date',
      'That local clock time does not exist in $timezone',
    );
  }
  return zoned.toUtc();
}

DateTime bookingRequestWallClock({
  required DateTime requestedForUtc,
  required String timezone,
}) {
  return bookingWallClockInZone(requestedForUtc, timezone);
}

BookingRequestHoursFit bookingRequestHoursFit({
  required DateTime requestedForUtc,
  required String timezone,
  required Map<String, dynamic> workingHours,
  int durationMinutes = 1,
}) {
  final wallClock = bookingRequestWallClock(
    requestedForUtc: requestedForUtc,
    timezone: timezone,
  );
  final published = workingHoursValueForDate(workingHours, wallClock);
  if (workingHourBlocks(published).isEmpty) {
    return BookingRequestHoursFit.noPublishedHours;
  }
  final start = bookingTimeInZone(requestedForUtc, timezone);
  final end = bookingTimeInZone(
    requestedForUtc.add(Duration(minutes: durationMinutes.clamp(1, 1440))),
    timezone,
  );
  return isWallClockWithinWorkingHours(
        hours: workingHours,
        start: start,
        end: end,
      )
      ? BookingRequestHoursFit.withinPublishedHours
      : BookingRequestHoursFit.outsidePublishedHours;
}
