import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.inputStream().use { keystoreProperties.load(it) }
}

val releaseTaskRequested = gradle.startParameter.taskNames.any {
    it.contains("Release", ignoreCase = true)
}
val firebaseConfigFile = file("google-services.json")
if (firebaseConfigFile.isFile) {
    // FlutterFire initializes the default app from resources generated by this
    // plugin. The downloaded file must match com.ismaeel.workloop.
    apply(plugin = "com.google.gms.google-services")
    apply(plugin = "com.google.firebase.crashlytics")
} else {
    if (releaseTaskRequested) {
        throw GradleException(
            "Android store builds require android/app/google-services.json " +
                "from the Workloop Firebase Android app."
        )
    }
    logger.warn(
        "Workloop: google-services.json is absent; Firebase push is unavailable " +
            "in this local build. Store builds require the real Firebase configuration."
    )
}

// Also protect aggregate task entry points such as `build` and `assemble`,
// whose requested names do not contain Release but include that variant.
tasks.matching { it.name == "preReleaseBuild" }.configureEach {
    doFirst {
        if (!firebaseConfigFile.isFile) {
            throw GradleException(
                "Android store builds require android/app/google-services.json."
            )
        }
    }
}
val requiredSigningProperties = listOf(
    "storeFile",
    "storePassword",
    "keyAlias",
    "keyPassword",
)
val missingSigningProperties = requiredSigningProperties.filter {
    keystoreProperties.getProperty(it).isNullOrBlank()
}
val releaseStoreFile = keystoreProperties.getProperty("storeFile")
    ?.takeIf { it.isNotBlank() }
    ?.let(rootProject::file)

if (releaseTaskRequested) {
    when {
        !keystorePropertiesFile.exists() -> throw GradleException(
            "Release signing is not configured. Copy android/key.properties.example " +
                "to android/key.properties and provide the Play signing credentials."
        )
        missingSigningProperties.isNotEmpty() -> throw GradleException(
            "Android release signing is missing: ${missingSigningProperties.joinToString()}."
        )
        releaseStoreFile?.isFile != true -> throw GradleException(
            "Android release signing storeFile does not exist: " +
                (releaseStoreFile?.path ?: "<not configured>")
        )
    }
}

android {
    namespace = "com.ismaeel.workloop"
    compileSdk = 36
    ndkVersion = flutter.ndkVersion

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "com.ismaeel.workloop"
        // Stripe Terminal 5.x requires API 26. Tap to Pay itself requires a
        // compatible Android 13+ NFC device at runtime.
        minSdk = 26
        targetSdk = 36
        multiDexEnabled = true
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        create("release") {
            if (missingSigningProperties.isEmpty() && releaseStoreFile?.isFile == true) {
                storeFile = releaseStoreFile
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            if (keystorePropertiesFile.exists()) {
                signingConfig = signingConfigs.getByName("release")
            }
            isDebuggable = false
            isJniDebuggable = false
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
    implementation("com.stripe:stripeterminal-taptopay:5.7.0")
    implementation("com.stripe:stripeterminal-core:5.7.0")
    implementation("com.stripe:stripeterminal-ktx:5.7.0")
    implementation("androidx.core:core-ktx:1.16.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
    // Bundled Latin OCR works immediately and keeps receipt images on-device.
    implementation("com.google.mlkit:text-recognition:16.0.1")
    implementation("androidx.exifinterface:exifinterface:1.4.1")
}

flutter {
    source = "../.."
}
